### ISSUE TITLE
Not able to build project on IOS

### ISSUE THREAD

**Issue by ashwaniKhuranaa** [Saranshmalik/react-native-zendesk#10] opened 2020-12-21 16:00 UTC
Hello 

When I installed and tried to build project in iOS it gives me error - Could not build project "ChatSDK"

**Comment by a396901990** [comment] 2020-12-24 15:14
same as me

**Comment by yatish3230** [comment] 2021-01-05 19:01
I am getting same error. i don't know what is the issue?

**Comment by Saranshmalik** [comment] 2021-01-28 07:55
Can you add more details to it. What RN version you guys using? I use this library on a production app and never had any issues so far, so some more details here would be helpful

**Comment by yungkittty** [comment] 2021-02-01 15:58
Hello @Saranshmalik, I'm getting these errors when i'm trying to build the ios app :

```
❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:18:3: use of undeclared identifier 'ZDKChatAPIConfiguration'

  ZDKChatAPIConfiguration *config = [[ZDKChatAPIConfiguration alloc] init];
                                                                                                                                        ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:18:28: use of undeclared identifier 'config'

  ZDKChatAPIConfiguration *config = [[ZDKChatAPIConfiguration alloc] init];
  ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:18:39: use of undeclared identifier 'ZDKChatAPIConfiguration'

  ZDKChatAPIConfiguration *config = [[ZDKChatAPIConfiguration alloc] init];
                           ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:20:5: use of undeclared identifier 'config'

    config.department = options[@"department"];
                                      ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:23:5: use of undeclared identifier 'config'

    config.tags = options[@"tags"];
    ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:25:3: use of undeclared identifier 'config'

  config.visitorInfo = [[ZDKVisitorInfo alloc] initWithName:options[@"name"]
    ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:25:26: use of undeclared identifier 'ZDKVisitorInfo'

  config.visitorInfo = [[ZDKVisitorInfo alloc] initWithName:options[@"name"]
  ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:28:3: use of undeclared identifier 'ZDKChat'

  ZDKChat.instance.configuration = config;
                         ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:28:36: use of undeclared identifier 'config'

  ZDKChat.instance.configuration = config;
  ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:30:91: use of undeclared identifier 'config'

  NSLog(@"Setting visitor info: department: %@ tags: %@, email: %@, name: %@, phone: %@", config.department, config.tags, config.visitorInfo.email, config.visitorInfo.name, config.visitorInfo.phoneNumber);
                                   ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:30:110: use of undeclared identifier 'config'

  NSLog(@"Setting visitor info: department: %@ tags: %@, email: %@, name: %@, phone: %@", config.department, config.tags, config.visitorInfo.email, config.visitorInfo.name, config.visitorInfo.phoneNumber);
                                                                                          ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:30:123: use of undeclared identifier 'config'

  NSLog(@"Setting visitor info: department: %@ tags: %@, email: %@, name: %@, phone: %@", config.department, config.tags, config.visitorInfo.email, config.visitorInfo.name, config.visitorInfo.phoneNumber);
                                                                                                             ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:30:149: use of undeclared identifier 'config'

  NSLog(@"Setting visitor info: department: %@ tags: %@, email: %@, name: %@, phone: %@", config.department, config.tags, config.visitorInfo.email, config.visitorInfo.name, config.visitorInfo.phoneNumber);
                                                                                                                          ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:30:174: use of undeclared identifier 'config'

  NSLog(@"Setting visitor info: department: %@ tags: %@, email: %@, name: %@, phone: %@", config.department, config.tags, config.visitorInfo.email, config.visitorInfo.name, config.visitorInfo.phoneNumber);
                                                                                                                                                    ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:34:5: use of undeclared identifier 'ZDKChatConfiguration'

    ZDKChatConfiguration *chatConfiguration = [[ZDKChatConfiguration alloc] init];
                                                                                                                                                                             ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:34:27: use of undeclared identifier 'chatConfiguration'

    ZDKChatConfiguration *chatConfiguration = [[ZDKChatConfiguration alloc] init];
    ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:34:49: use of undeclared identifier 'ZDKChatConfiguration'

    ZDKChatConfiguration *chatConfiguration = [[ZDKChatConfiguration alloc] init];
                          ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:36:9: unknown type name 'chatConfiguration'; did you mean 'UIPasteConfiguration'?

        chatConfiguration.chatMenuActions = options[@"chatMenuActions"];
                                                ^



❌  /Users/yungkittty/Clones/b2c-app/node_modules/react-native-zendesk-v2/ios/RNZendeskChat.m:36:9: use of undeclared identifier 'chatConfiguration'

        chatConfiguration.chatMenuActions = options[@"chatMenuActions"];
           ^



❌  fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

I'm using React Native 0.63.3 and the latest version of the package.

**Comment by Saranshmalik** [comment] 2021-02-04 10:01
This feels like, Pods not available, could you confirm you did pod install after installing the package and then make sure you see Zendesk Pods in your project.

**Comment by yatish3230** [comment] 2021-02-04 15:59
Hi Saranshmalik
Problem is in particular ios. ZDKChat is giving some error while importing
it. It says It doen't find any thing like this.
so all the things from ZDKChat in RNZendesk file is throwing error.

**Comment by Saranshmalik** [comment] 2021-02-06 15:00
But do you see Zendesk SDKs in your pods? I use this package in a production app and see no issues in builds. Please make sure pods are installed and let me know

**Comment by yungkittty** [comment] 2021-02-06 22:49
I have found the source of my errors. They were due to my native react configuration (several schemas). If this is your case too, here is the fix :

```
project 'awesome',
        'Dev.Debug' => :debug,
        'Dev.Release' => :release, 
        'Qa.Debug' => :debug,
        'Qa.Release' => :release, 
        'Prod.Debug' => :debug,
        'Prod.Release' => :release
```

http://blog.logicwind.com/adding-multiple-target/

**Comment by ajw-m** [comment] 2021-02-10 23:05
I'm not using several schemas. What worked for me is going to Pods => Selecting the pod (RNZendeskChat) and going to Build Settings tab => Build Active Architecture Only => Release => **Yes**

The Release value was No for me.
Hope this helps.

**Comment by yungkittty** [comment] 2021-02-10 23:18
@ajw-m In fact both are related, in both case release wasn't set to true in some ways!

**Comment by heavyskyl** [comment] 2021-02-11 11:09
Did not help me on react-native 0.63.2.

**Comment by ajw-m** [comment] 2021-02-11 20:34
> Did not help me on react-native 0.63.2.

You're having the same error and you tried all of the steps above? Is the error also in "Release"?

**Comment by nelsona** [comment] 2021-02-25 11:02
I am having a similar error, the issue is when trying to run a Release config on the simulator. 

Running a release build with the following configuration causes the build to fail:

`xcodebuild -workspace ios/app.xcworkspace -scheme app -configuration Release -sdk iphonesimulator -derivedDataPath ios/build`

**Comment by ajw-m** [comment] 2021-03-02 00:00
@nelsona any errors?

**Comment by Saranshmalik** [comment] 2021-03-27 13:30
This should be fixed, please update the version and let me know if any one still faces these issues.

**Closed** 2021-03-27 13:29 UTC
Labels: Incomplete Information
